# Setup max number of unavailable pods in StatefulSet
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clickhouse-keeper-pod-disruption-budget
spec:
  selector:
    matchLabels:
      {{- include "clickhouse-keeper.selectorLabels" . | nindent 6 }}
  maxUnavailable: 1
